name: cashcam
description: A Flutter application to recognize coins and bills.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  path_provider: ^2.0.11
  path: ^1.8.3
  http: ^1.2.1
  image_picker: ^0.8.4+8
  google_sign_in: ^5.0.7
  flutter_exif_rotation: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_icon.png
    - assets/logo.jpeg
    - assets/USD_C_1.png
    - assets/USD_C_5.png
    - assets/USD_C_10.png
    - assets/USD_C_25.png
    - assets/USD_C_50.png
    - assets/USD_C_100.png
    - assets/USD_B_1.png
    - assets/USD_B_2.png
    - assets/USD_B_5.png
    - assets/USD_B_10.png
    - assets/USD_B_20.png
    - assets/USD_B_50.png
    - assets/USD_B_100.png
    - assets/EUR_C_1.png
    - assets/EUR_C_2.png
    - assets/EUR_C_5.png
    - assets/EUR_C_10.png
    - assets/EUR_C_20.png
    - assets/EUR_C_50.png
    - assets/EUR_C_100.png
    - assets/EUR_C_200.png
    - assets/EUR_B_5.png
    - assets/EUR_B_10.png
    - assets/EUR_B_20.png
    - assets/EUR_B_50.png
    - assets/EUR_B_100.png
    - assets/EUR_B_200.png
    - assets/EUR_B_500.png
    - assets/NIS_C_10.png
    - assets/NIS_C_50.png
    - assets/NIS_C_100.png
    - assets/NIS_C_200.png
    - assets/NIS_C_500.png
    - assets/NIS_C_1000.png
    - assets/NIS_B_20.png
    - assets/NIS_B_50.png
    - assets/NIS_B_100.png
    - assets/NIS_B_200.png
